apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.serviceName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ServiceType }}
  ports:
    {{- range $ref := .Values.services }}
    - port: {{ $ref.port }}
      targetPort: {{ $ref.targetPort }}
      protocol: {{ $ref.protocol }}
      name: {{ $ref.name }}
    {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
